import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { PT_Sans } from "next/font/google";
import { Playpen_Sans } from "next/font/google";
import "./globals.css";

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400"],
});

const pt_sans_init = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const playpen_sans_init = Playpen_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Soyeon's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playpen_sans_init.className}>{children}</body>
    </html>
  );
}
